apiVersion: v1
kind: Secret
metadata:
  name: coiled-auth
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.auth.coiled.username | quote }}
  password: {{ .Values.auth.coiled.accessToken | quote }}