apiVersion: v1
kind: Secret
metadata:
  name: github-auth
type: kubernetes.io/basic-auth
stringData:
  username: {{
    required "GitHub username must be specified to store flows on GitHub"
    .Values.auth.github.username | quote 
  }}
  password: {{
    required "GitHub access token must be specified to store flows on GitHub"
    .Values.auth.github.accessToken | quote
  }}